version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy

  web-blue-01:
    image: fabricioveronez/web-page:blue
    networks:
      - proxy

  web-blue-02:
    image: fabricioveronez/web-page:blue
    networks:
      - proxy

  web-green-01:
    image: fabricioveronez/web-page:green
    networks:
      - proxy

  web-green-02:
    image: fabricioveronez/web-page:green
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
